// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./components/AdminHeader.vue')['default']
    ButtonComponent: typeof import('./components/ButtonComponent.vue')['default']
    ButtonLink: typeof import('./components/ButtonLink.vue')['default']
    MoonIcon: typeof import('./components/icons/MoonIcon.vue')['default']
    NavHeader: typeof import('./components/NavHeader.vue')['default']
    NotificationContainer: typeof import('./components/NotificationContainer.vue')['default']
    PopUp: typeof import('./components/PopUp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SunIcon: typeof import('./components/icons/SunIcon.vue')['default']
  }
}

export {}
